# Generated by Django 6.0.7 on 2026-07-27 20:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio_cobrado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duracion_minutos', models.IntegerField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada'), ('NO_ASISTIO', 'No Asistió')], default='PENDIENTE')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('telefono', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('notas_internas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_hero', models.TextField(blank=True, null=True)),
                ('subtitulo_hero', models.TextField(blank=True, null=True)),
                ('imagen_hero_url', models.TextField(blank=True, null=True)),
                ('texto_footer', models.TextField(blank=True, null=True)),
                ('instagram_url', models.TextField(blank=True, null=True)),
                ('facebook_url', models.TextField(blank=True, null=True)),
                ('tiktok_url', models.TextField(blank=True, null=True)),
                ('mostrar_precios', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configuracion_landing',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('nit', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp', models.TextField(blank=True, null=True)),
                ('moneda', models.TextField(default='COP')),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('color_primario', models.TextField(default='#db2777')),
                ('color_secundario', models.TextField(default='#fff0f5')),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EventoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('tipo', models.TextField(choices=[('GENERAL', 'General'), ('LICENCIA', 'Licencia'), ('PAGO', 'Pago'), ('SOPORTE', 'Soporte')], default='GENERAL')),
                ('completado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evento_empresa',
            },
        ),
        migrations.CreateModel(
            name='LicenciaToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('estado', models.TextField(choices=[('DISPONIBLE', 'Disponible'), ('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada')], default='DISPONIBLE')),
            ],
            options={
                'db_table': 'licencia_token',
            },
        ),
        migrations.CreateModel(
            name='PlanLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_citas_mes', models.IntegerField(blank=True, null=True)),
                ('max_servicios', models.IntegerField(blank=True, null=True)),
                ('max_usuarios_admin', models.IntegerField(blank=True, null=True)),
                ('max_sucursales', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'plan_licencia',
            },
        ),
        migrations.CreateModel(
            name='RenovacionLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_renovacion', models.DateTimeField(auto_now_add=True)),
                ('meses_agregados', models.IntegerField()),
                ('nueva_fecha_vencimiento', models.DateTimeField()),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'renovacion_licencia',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
    ]
