# Generated by Django 6.0.7 on 2026-07-27 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='empresas.cliente'),
        ),
        migrations.AddField(
            model_name='configuracionlanding',
            name='empresa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='cita',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='eventoempresa',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='licenciatoken',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='empresas.empresa'),
        ),
    ]
