# Generated by Django 6.0.7 on 2026-07-27 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciatoken',
            name='generada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_generadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='licenciatoken',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias', to='empresas.planlicencia'),
        ),
        migrations.AddField(
            model_name='renovacionlicencia',
            name='licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones', to='empresas.licenciatoken'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='cita',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='empresas.sucursal'),
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('empresa', 'telefono')},
        ),
        migrations.AddIndex(
            model_name='licenciatoken',
            index=models.Index(fields=['empresa', 'estado'], name='licencia_to_empresa_199cd6_idx'),
        ),
        migrations.AddIndex(
            model_name='licenciatoken',
            index=models.Index(fields=['fecha_vencimiento'], name='licencia_to_fecha_v_e03446_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['empresa', 'fecha'], name='cita_empresa_62ed9a_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['empresa', 'estado'], name='cita_empresa_8124aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('empresa', 'sucursal', 'servicio', 'fecha', 'hora')},
        ),
    ]
