# Generated by Django 6.0.7 on 2026-08-06

from django.db import migrations


class Migration(migrations.Migration):
    """Keep the database table aligned with Usuario.Meta.db_table.

    The first migration was created while the custom user model still reused
    ``auth_user``.  The model now correctly owns ``usuario``; without this
    migration a fresh login queries a table that has never been created.
    """

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
